---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kon-ns
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: kafka
      #hosts: ["172.16.101.123:32092"]
      hosts: ["192.168.199.99:32092"]
      topics: ["temperature"]
      group_id: "xiiot-kafka"
      
    #processors:
    #- decode_json_fields:
    #    fields: ["message"]

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      pipeline: "temp_pipeline"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: filebeat
  namespace: kon-ns
spec:
  serviceName: filebeat
  selector:
    matchLabels:
      app: filebeat
  replicas: 1
  template:
    metadata:
      name: filebeat
      labels:
        app: filebeat
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.8.0
        ports:
        - containerPort: 9200
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
